### ISSUE TITLE
Error on windows: error: failed to prepare transaction (could not find database)

### ISSUE THREAD

**Issue by AJ-Ianozi** [alire-project/setup-alire#42]
I'm currently using setup-alire in my workflows for [GetAda](https://github.com/AJ-Ianozi/getada) and while it's working fine on Mac and Linux, [it's currently Failing on Windows](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644).

[This is the specific step that is failing](https://github.com/AJ-Ianozi/getada/blob/d5a036bd1e42b3d09c4ed5de16e1202ee3658a1d/.github/workflows/build.yml#L46):
```
      - name: Set up alire
        uses: alire-project/setup-alire@v1
```

I re-ran it with debugging, and these are the results that I got...  Any ideas?  It was working before.

```
##[debug]Evaluating condition for step: 'Set up alire'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Set up alire
##[debug]Loading inputs
##[debug]Loading env
Run alire-project/setup-alire@v1
Deploying alr version [1.[2](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644#step:3:2).1]
Downloading file: https://github.com/alire-project/alire/releases/download/v1.2.1/alr-1.2.1-bin-x86_64-windows.zip to alire_install
##[debug]Downloading https://github.com/alire-project/alire/releases/download/v1.2.1/alr-1.2.1-bin-x86_64-windows.zip
##[debug]Destination D:\a\_temp\[3](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644#step:3:3)052dcbc-de8d-[4](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644#step:3:4)6c6-b93e-41ee482a81b9
##[debug]download complete
##[debug]Using pwsh at path: C:\Program Files\PowerShell\7\pwsh.exe
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.ZipFile } catch { } ; try { [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\30[5](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644#step:3:5)2dcbc-de8d-4[6](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644#step:3:6)c6-b93e-41ee482a81b9', 'alire_install', $true) } catch { if (($_.Exception.GetType().FullName -eq 'System.Management.Automation.MethodException') -or ($_.Exception.GetType().FullName -eq 'System.Management.Automation.RuntimeException') ){ Expand-Archive -LiteralPath 'D:\a\_temp\3052dcbc-de8d-46c6-b93e-41ee482a81b9' -DestinationPath 'alire_install' -Force } else { throw $_ } } ;"
D:\a\getada\getada\alire_install\bin\alr.exe -n toolchain --select gnat_native gprbuild
Alire can use the msys2 Windows system package manager to provide easy install
of tools (git, unzip, make, etc.) as well as libraries (libsdl, libusb, etc.)
The use of msys2 is recommend for a better user experience.
(msys2 will be installed in 'C:\Users\runneradmin\.cache\alire\msys64').
Do you want Alire to install msys2? (recommended)
Using default: Yes
#=#=#                                                                         
##O#-#                                                                        
##O=#  #                                                                      

                                                                           0.0%
                                                                           0.1%
                                                                           0.3%
                                                                           0.8%
#                                                                          2.0%
###                                                                        4.4%
######                                                                     8.[7](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644#step:3:7)%
#########                                                                 13.0%
##############                                                            20.7%
##################                                                        26.0%
########################                                                  34.7%
##############################                                            41.7%
#################################                                         47.0%
#####################################                                     51.9%
###########################################                               60.6%
##############################################                            64.9%
####################################################                      73.2%
########################################################                  77.9%
##############################################################            [8](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644#step:3:8)6.6%

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 pacman-6.0.1-28-x86_64 downloading...
 msys2-runtime-3.4.3-4-x86_64 downloading...
 bash-5.2.00[9](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644#step:3:9)-1-x86_64 downloading...
 mintty-1~3.6.3-1-x86_64 downloading...
 filesystem-2022.01-7-x86_64 downloading...
 pacman-mirrors-20221016-1-any downloading...
checking keyring...
error: failed retrieving file 'mintty-1~3.6.3-1-x86_64.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'pacman-6.0.1-28-x86_64.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'filesystem-2022.01-7-x86_64.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: too many errors from mirror.msys2.org, skipping for the remainder of this transaction
error: failed retrieving file 'msys2-runtime-3.4.3-4-x86_64.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
upgrading bash...
upgrading filesystem...
upgrading mintty...
upgrading msys2-runtime...
upgrading pacman-mirrors...
upgrading pacman...
:: To complete this update all MSYS2 processes including this terminal will be closed. Confirm to proceed [Y/n] 
warning: database file for 'clangarm64' does not exist (use '-Sy' to download)
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
error: failed to prepare transaction (could not find database)

raised ALIRE.CHECKED_ERROR : alire-stored-error:1
[D:\a\getada\getada\alire_install\bin\alr.exe]
0xdc8cdb Semantic_Versioning.Basic.At_Least at alire.adb:251
0xa63c02 Semantic_Versioning.Basic.At_Least at alire-os_lib-subprocess.adb:110
0xa6d7d1 Semantic_Versioning.Basic.At_Least at alire-platforms-current__windows.adb:326
0xa6f6a3 Semantic_Versioning.Basic.At_Least at alire-platforms-current__windows.adb:374
0xa6fbb7 Semantic_Versioning.Basic.At_Least at alire-platforms-current__windows.adb:396
0x403f25 Adainit at b__alr-main.adb:1848
0x404bd1 Main at b__alr-main.adb:2129
0x401423 __tmainCRTStartup at ???
0x401[13](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644#step:3:14)b mainCRTStartup at ???
[C:\Windows\System32\KERNEL32.DLL]
0x7ffb93cc4dde
[C:\Windows\SYSTEM32\ntdll.dll]
0x7ffb9533e409
ERROR: Command ["pacman", "--noconfirm", "-Su"] exited with code 1
ERROR: alr encountered an unexpected error, re-run with -d for details.
Error: The process 'D:\a\getada\getada\alire_install\bin\alr.exe' failed with exit code 1
    at ExecState._setResult (D:\a\_actions\alire-project\setup-alire\v1\node_modules\@actions\exec\lib\toolrunner.js:592:25)
    at ExecState.CheckComplete (D:\a\_actions\alire-project\setup-alire\v1\node_modules\@actions\exec\lib\toolrunner.js:575:18)
    at ChildProcess.<anonymous> (D:\a\_actions\alire-project\setup-alire\v1\node_modules\@actions\exec\lib\toolrunner.js:469:27)
    at ChildProcess.emit (events.js:3[14](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644#step:3:15):20)
    at maybeClose (internal/child_process.js:1022:[16](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644#step:3:17))
    at Process.ChildProcess._handle.onexit (internal/child_process.js:[28](https://github.com/AJ-Ianozi/getada/actions/runs/3863415633/jobs/6585623644#step:3:29)7:5)
Error: The process 'D:\a\getada\getada\alire_install\bin\alr.exe' failed with exit code 1
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Set up alire
```

**Comment by Fabien-Chouteau** [comment]
Hello @AJ-Ianozi we are aware of this problem (See https://github.com/alire-project/alire/issues/1283).
